
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: halayersets.app.hasno.com
spec:
  group: app.hasno.com
  names:
    kind: HALayerSet
    listKind: HALayerSetList
    plural: halayersets
    singular: halayerset
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HALayerSet is the Schema for the halayersets API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HALayerSetSpec defines the desired state of HALayerSet
            properties:
              deployments:
                description: Deployments is a list of deployments that will be managed
                  by the created HA layer.
                items:
                  type: string
                type: array
              fenceAgentsSpec:
                description: FenceAgentsSpec list of fence agent to use during HA
                  layer fencing setup.
                items:
                  description: FenceAgentSpec contains the necessary information for
                    setting up the fence agent that will be used in the HA layer.
                  properties:
                    name:
                      description: Name fence agent name.
                      type: string
                    params:
                      additionalProperties:
                        type: string
                      description: 'Params parameters which are necessary when creating
                        the fence agent, will be applied in the format: key1=value1
                        key2=value2 ...'
                      type: object
                    type:
                      description: Type of the fence agent.
                      type: string
                  required:
                  - name
                  - type
                  type: object
                type: array
              nodesSpec:
                description: NodesSpec contain names and ips of both SNO clusters
                  nodes.
                properties:
                  firstNodeIP:
                    description: FirstNodeIP is the ip address used by the first node
                      in the cluster.
                    type: string
                  firstNodeName:
                    description: FirstNodeName is the name of the first node in the
                      cluster.
                    type: string
                  secondNodeIP:
                    description: SecondNodeIP is the ip address used by the second
                      node in the cluster.
                    type: string
                  secondNodeName:
                    description: SecondNodeName is the name of the second node in
                      the cluster.
                    type: string
                required:
                - firstNodeIP
                - firstNodeName
                - secondNodeIP
                - secondNodeName
                type: object
            required:
            - fenceAgentsSpec
            - nodesSpec
            type: object
          status:
            description: HALayerSetStatus defines the observed state of HALayerSet
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
